import React, { useEffect, useMemo, useRef, useState } from 'react'
import { DEFAULT_CLOSE_TASKS, DEFAULT_FIELD_DICTIONARY, FINANCE_MODULES, FINANCE_WORKFLOWS, NAV_GROUPS, SOP_STEPS, WORKFLOW_GROUPS, defaultFinanceTodos } from './finance-data.js'
import { buildFinanceBackup, closeProgress, dueLabel, emptyFinanceSnapshot, greetingFor, localDateKey, normalizeFinanceSnapshot, normalizeTodo, parseFinanceBackup, snapshotProfit, workflowsForView } from './finance-dashboard-helpers.js'
import { defaultPinnedPaths, fileKind, filterFiles, matchScenarioFiles, orderFiles, summarizeFiles, topFolder } from './ui-helpers.js'

const STORE_PREFIX = 'dshFinance:desk:v2:'
const TYPE_LABELS = { all: '全部类型', document: '文档', sheet: '表格', slides: '演示', image: '图片', other: '其他' }
const PROFILE_DEFAULT = { name: '财务伙伴', entity: '示例财务工作区', role: '财务自动化与管理分析', period: localDateKey().slice(0, 7) }
const SETTINGS_DEFAULT = { largeAmount: 100000, dateTolerance: 3, varianceRate: 10 }
const PAGE_META = {
  home: ['财务总览', '收入、支出、利润、资金与往来的一站式视图'],
  todos: ['待办中心', '责任、截止与完成留痕'], workflows: ['自动化工作流', '25 个标准场景与专业扩展'],
  files: ['财务资料库', '上传、搜索、引用、下载与置顶'], close: ['月结中心', '完成证据、异常责任与风险复核'],
  backup: ['数据备份', '设置、台账与操作记录的本机备份'], settings: ['系统设置', '个人信息、业务阈值与字段口径'],
  ...Object.fromEntries(Object.entries(FINANCE_MODULES).map(([key, module]) => [key, [module.title, module.intro]])),
}
const SNAPSHOT_FIELDS = [['income', '本月收入'], ['expense', '本月支出'], ['cash', '可用资金'], ['receivable', '应收余额'], ['payable', '应付余额'], ['budget', '预算额度']]
const TODO_CATEGORIES = ['通用', '收入', '应收', '应付', '报销', '资金', '预算', '资产', '税务', '发票', '工资', '对账', '成本', '报表', '分析', '投资', '审计', '月结']

function clone(value) { return JSON.parse(JSON.stringify(value)) }
function readStore(key, fallback) { try { const value = JSON.parse(localStorage.getItem(`${STORE_PREFIX}${key}`)); return value ?? clone(fallback) } catch { return clone(fallback) } }
function useStoredState(key, fallback) { const initial = typeof fallback === 'function' ? fallback() : fallback; const [value, setValue] = useState(() => readStore(key, initial)); useEffect(() => { try { localStorage.setItem(`${STORE_PREFIX}${key}`, JSON.stringify(value)) } catch {} }, [key, value]); return [value, setValue] }
function makeId(prefix) { return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}` }
function downloadJson(value, name) { const blob = new Blob([JSON.stringify(value, null, 2)], { type: 'application/json;charset=utf-8' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 3000) }
function formatSize(bytes) { if (bytes < 1024) return `${bytes} B`; if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`; return `${(bytes / 1024 / 1024).toFixed(1)} MB` }
function formatDate(value) { return new Intl.DateTimeFormat('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }).format(new Date(value)) }
function formatMoney(value) { if (value === '' || value === null || value === undefined || !Number.isFinite(Number(value))) return '待录入'; return `¥${Number(value).toLocaleString('zh-CN', { maximumFractionDigits: 0 })}` }

function Panel({ title, note, action, className = '', children }) { return <section className={`fdDesk_panel ${className}`}><header className="fdDesk_panelHead"><div><h3>{title}</h3>{note && <p>{note}</p>}</div>{action}</header>{children}</section> }

function WorkflowCards({ workflows, favorites, onSelect }) {
  if (!workflows.length) return <div className="fdDesk_empty">没有符合条件的工作流</div>
  return <div className="fdDesk_workflowGrid">{workflows.map(item => <button type="button" key={item.id} onClick={() => onSelect(item)}><span>{item.number || '扩展'} · {item.role}</span><strong>{item.title}</strong><small>{item.desc}</small><i>{favorites.includes(item.id) ? '★' : '☆'}</i></button>)}</div>
}

function WorkflowDetail({ workflow, files, favorites, launching, onBack, onFavorite, onLaunch, onChooseFiles, onChooseFolder }) {
  const matched = useMemo(() => matchScenarioFiles(files, workflow), [files, workflow])
  return <div className="fdDesk_page fdDesk_detail"><button className="fdDesk_textButton" type="button" onClick={onBack}>← 返回工作流</button><div className="fdDesk_detailHero"><div><small>{workflow.number ? `SOP ${workflow.number}` : '专业扩展'} · {workflow.role}</small><h1>{workflow.title}</h1><p>{workflow.desc}</p></div><span>人工复核</span></div><div className="fdDesk_detailGrid"><Panel title="输入材料" note="先确认版本、期间、主体和字段"><ul className="fdDesk_list">{workflow.inputs.map(item => <li key={item}>{item}</li>)}</ul></Panel><Panel title="关键规则" note="规则不清楚时先诊断，不直接跑全量"><ul className="fdDesk_list is-rules">{workflow.rules.map(item => <li key={item}>{item}</li>)}</ul></Panel></div><Panel title="7 步执行路径" note="先方案、再小样本、后全量、最后固化"><ol className="fdDesk_steps">{workflow.steps.map((item, index) => <li key={item}><span>{index + 1}</span><strong>{item}</strong></li>)}</ol></Panel><div className="fdDesk_detailGrid"><Panel title="固定输出包" note="所有结果都要有来源与校验"><div className="fdDesk_outputPills">{workflow.outputs.map(item => <span key={item}>{item}</span>)}</div></Panel><Panel title="验收清单" note="通过后才能进入正式复核"><ul className="fdDesk_checkList">{workflow.checklist.map(item => <li key={item}>□ {item}</li>)}</ul></Panel></div><Panel title="自动匹配资料" note={matched.length ? `已找到 ${matched.length} 份相关文件` : '暂未找到明显相关文件，可先上传或直接开始后补充'} action={<div className="fdDesk_inlineActions"><button type="button" onClick={onChooseFiles}>上传文件</button><button type="button" onClick={onChooseFolder}>上传文件夹</button></div>}>{matched.length ? <div className="fdDesk_matchFiles">{matched.map(file => <span key={file.relative}>{file.name}</span>)}</div> : <div className="fdDesk_empty is-compact">系统还会结合当前对话理解任务范围。</div>}</Panel><div className="fdDesk_launchBar"><div><strong>执行边界</strong><span>只处理副本 · 不覆盖源文件 · 异常不等于结论 · 付款、入账与申报由人工确认</span></div><button type="button" disabled={launching} onClick={() => onLaunch(workflow)}>{launching ? '正在准备…' : '开始处理'}</button><button type="button" className="is-secondary" onClick={() => onFavorite(workflow.id)}>{favorites.includes(workflow.id) ? '取消收藏' : '收藏'}</button></div></div>
}

function SnapshotEditor({ draft, setDraft, onSave }) { return <Panel title="经营快照" note="只录入汇总数，随时可以覆盖本期数据" action={<span className="fdDesk_periodTag">{draft.period}</span>}><form className="fdDesk_snapshotForm" onSubmit={onSave}>{SNAPSHOT_FIELDS.map(([key, label]) => <label key={key}>{label}<input type="number" min="0" step="0.01" value={draft[key]} onChange={event => setDraft(current => ({ ...current, [key]: event.target.value }))} placeholder="0"/></label>)}<label className="is-wide">备注<input value={draft.note} maxLength={300} onChange={event => setDraft(current => ({ ...current, note: event.target.value }))} placeholder="例如：收入变化主要来自续费回款"/></label><button type="submit">保存本期快照</button></form></Panel> }

function TrendChart({ snapshots }) {
  const rows = [...snapshots].sort((a, b) => a.period.localeCompare(b.period)).slice(-6)
  const max = Math.max(1, ...rows.flatMap(row => [Number(row.income) || 0, Number(row.expense) || 0]))
  if (!rows.length) return <div className="fdDesk_empty fdDesk_chartEmpty">录入经营快照后，这里会自动生成近 6 期趋势。</div>
  return <div className="fdDesk_trend" aria-label="近6期收支趋势">{rows.map(row => <div className="fdDesk_trendGroup" key={row.period}><div className="fdDesk_bars"><i className="is-income" style={{ height: `${Math.max(4, (Number(row.income) || 0) / max * 100)}%` }} title={`收入 ${formatMoney(row.income)}`}/><i className="is-expense" style={{ height: `${Math.max(4, (Number(row.expense) || 0) / max * 100)}%` }} title={`支出 ${formatMoney(row.expense)}`}/></div><span>{Number(row.period.slice(5))}月</span></div>)}</div>
}

function OverviewPage({ profile, snapshot, snapshots, draft, setDraft, saveSnapshot, activeTodos, setTodos, progress, closeTasks, featured, favorites, summary, changeView, onSelectWorkflow }) {
  const profit = snapshotProfit(snapshot)
  const kpis = [['income', '本月收入', 'revenue'], ['expense', '本月支出', 'expenses'], ['profit', '本月利润', 'analysis'], ['cash', '可用资金', 'treasury'], ['receivable', '应收余额', 'receivables'], ['payable', '应付余额', 'payables']]
  return <div className="fdDesk_page"><div className="fdDesk_greeting"><div><small>FINANCE OPERATIONS DESK</small><h1>{greetingFor()}，{profile.name}</h1><p>{profile.period} · {profile.entity} · 从经营数字直接进入责任、流程与交付物。</p></div><button type="button" onClick={() => changeView('workflows')}>开始一项财务工作</button></div><div className="fdDesk_kpis">{kpis.map(([key, label, target]) => <button type="button" key={key} onClick={() => changeView(target)}><span>{label}</span><strong>{formatMoney(key === 'profit' ? profit : snapshot[key])}</strong><small>{key === 'profit' ? '收入－支出' : '点击进入专业模块'}</small></button>)}</div><div className="fdDesk_overviewGrid"><SnapshotEditor draft={draft} setDraft={setDraft} onSave={saveSnapshot}/><Panel title="近 6 期收支趋势" note="绿色为收入，棕色为支出" action={<button className="fdDesk_textButton" type="button" onClick={() => changeView('analysis')}>进入分析 →</button>}><TrendChart snapshots={snapshots}/></Panel></div><Panel title="财务全流程" note="从业务发生到报表复核，点击节点进入对应工作区"><div className="fdDesk_flow">{[['收入确认', 'revenue'], ['开票管理', 'invoices'], ['应收跟进', 'receivables'], ['资金收付', 'treasury'], ['银行对账', 'reconcile'], ['报表分析', 'statements']].map(([label, target], index) => <React.Fragment key={target}><button type="button" onClick={() => changeView(target)}><span>{index + 1}</span><strong>{label}</strong></button>{index < 5 && <i>→</i>}</React.Fragment>)}</div></Panel><div className="fdDesk_homeGrid"><Panel title="本期待办" note={`${activeTodos.length} 项待处理`} action={<button className="fdDesk_textButton" type="button" onClick={() => changeView('todos')}>查看全部 →</button>}><div className="fdDesk_todoPreview">{activeTodos.slice(0, 5).map(item => <article key={item.id}><i className={`is-${item.priority}`}/><div><strong>{item.text}</strong><small>{item.category} · {dueLabel(item.due)}</small></div><button type="button" onClick={() => setTodos(current => current.map(row => row.id === item.id ? { ...row, done: true } : row))}>完成</button></article>)}{!activeTodos.length && <div className="fdDesk_empty">本期待办已完成</div>}</div></Panel><Panel title="月结与内控" note={`${progress.done}/${progress.total} 项有完成证据`} action={<strong className="fdDesk_percent">{progress.percent}%</strong>}><div className="fdDesk_progress"><i style={{ width: `${progress.percent}%` }}/></div><div className="fdDesk_closePreview">{closeTasks.filter(item => !item.done).slice(0, 4).map(item => <button type="button" key={item.id} onClick={() => changeView('close')}><span>待核</span><div><strong>{item.title}</strong><small>{item.owner}</small></div></button>)}</div></Panel></div><Panel title="常用工作流" note={`${summary.total} 份资料可被工作流引用`} action={<button className="fdDesk_textButton" type="button" onClick={() => changeView('workflows')}>全部 25 个 →</button>}><WorkflowCards workflows={featured.length ? featured : FINANCE_WORKFLOWS.slice(0, 4)} favorites={favorites} onSelect={onSelectWorkflow}/></Panel></div>
}

function ManagementModulePage({ module, snapshot, todos, workflows, favorites, onSelect, onNewTodo, onFiles }) {
  const profit = snapshotProfit(snapshot)
  const todoCount = todos.filter(item => !item.done && module.todoCategories.includes(item.category)).length
  return <div className="fdDesk_page"><div className="fdDesk_moduleHero fdDesk_moduleHeroPro"><div><small>{module.eyebrow} · {module.category}</small><h1>{module.title}</h1><p>{module.intro}</p><div><button type="button" onClick={() => workflows[0] && onSelect(workflows[0])}>启动推荐工作流</button><button type="button" className="is-secondary" onClick={onNewTodo}>新建模块待办</button><button type="button" className="is-secondary" onClick={onFiles}>打开资料库</button></div></div><span>{workflows.length}<small>个适用场景</small></span></div><div className="fdDesk_moduleMetrics">{module.snapshotKeys.map(([label, key]) => <article key={key}><span>{label}</span><strong>{formatMoney(key === 'profit' ? profit : snapshot[key])}</strong></article>)}<article><span>未完成待办</span><strong>{todoCount}</strong></article><article><span>关键控制点</span><strong>{module.controls.length}</strong></article></div><Panel title="标准处理链路" note="每一步都有输入、判断与可交付结果"><ol className="fdDesk_process">{module.process.map(([title, note], index) => <li key={title}><span>{String(index + 1).padStart(2, '0')}</span><div><strong>{title}</strong><small>{note}</small></div></li>)}</ol></Panel><div className="fdDesk_moduleColumns"><Panel title="关键控制" note="优先检查高影响、不可逆和跨系统事项"><ul className="fdDesk_controlList">{module.controls.map(item => <li key={item}>{item}</li>)}</ul></Panel><Panel title="固定交付物" note="输出名称固定，方便复核、检索与归档"><div className="fdDesk_deliverables">{module.deliverables.map((item, index) => <article key={item}><span>{index + 1}</span><strong>{item}</strong></article>)}</div></Panel></div><Panel title="适用 AI 工作流" note="先看规则与样本，再由人工确认正式结果"><WorkflowCards workflows={workflows} favorites={favorites} onSelect={onSelect}/></Panel></div>
}

function FileLibrary({ files, workspace, onOpenWorkspace, onChooseFiles, onChooseFolder, onUploadFiles, onReferenceFile, onDownloadFile, onStatus, onAudit }) {
  const [query, setQuery] = useState(''); const [kind, setKind] = useState('all'); const [folder, setFolder] = useState('all'); const [order, setOrder] = useState('recent'); const [dragging, setDragging] = useState(false); const [pinned, setPinned] = useStoredState('pinnedFiles', [])
  useEffect(() => { if (!files.length || pinned.length) return; const defaults = defaultPinnedPaths(files); if (defaults.length) setPinned(defaults) }, [files.length])
  const summary = useMemo(() => summarizeFiles(files), [files]); const folders = useMemo(() => [...new Set(files.map(file => topFolder(file.relative)))].sort((a, b) => a.localeCompare(b, 'zh-CN')), [files]); const visible = useMemo(() => orderFiles(filterFiles(files, query, kind, folder), pinned, order), [files, query, kind, folder, pinned, order])
  const togglePin = path => { const pinning = !pinned.includes(path); setPinned(current => current.includes(path) ? current.filter(item => item !== path) : [...current, path]); onAudit('资料库', pinning ? '置顶文件' : '取消置顶', path); onStatus('资料库置顶已更新') }
  return <div className="fdDesk_page"><div className="fdDesk_directory"><span>库</span><div><small>当前财务资料目录</small><strong>{workspace.name}</strong><em title={workspace.path}>{workspace.path || '等待工作区准备'}</em></div><button type="button" onClick={onOpenWorkspace}>在 Finder 打开</button></div><div className={`fdDesk_dropzone ${dragging ? 'is-dragging' : ''}`} onDragEnter={event => { event.preventDefault(); setDragging(true) }} onDragOver={event => event.preventDefault()} onDragLeave={event => { if (event.currentTarget === event.target) setDragging(false) }} onDrop={event => { event.preventDefault(); setDragging(false); onUploadFiles([...event.dataTransfer.files]) }}><span>＋</span><div><strong>上传并存档财务资料</strong><small>支持文件、文件夹和拖放；原始文件不会被覆盖。</small></div><button type="button" onClick={onChooseFiles}>选择文件</button><button type="button" onClick={onChooseFolder}>选择文件夹</button></div><div className="fdDesk_fileStats">{[['文件', summary.total], ['表格', summary.sheet], ['文档', summary.document], ['图片', summary.image], ['总大小', formatSize(summary.bytes)]].map(([label, value]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><div className="fdDesk_fileFilters"><input value={query} onChange={event => setQuery(event.target.value)} placeholder="搜索文件名或目录"/><select value={kind} onChange={event => setKind(event.target.value)}>{Object.entries(TYPE_LABELS).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select><select value={folder} onChange={event => setFolder(event.target.value)}><option value="all">全部目录</option>{folders.map(item => <option key={item} value={item}>{item}</option>)}</select><select value={order} onChange={event => setOrder(event.target.value)}><option value="recent">最近更新</option><option value="name">按名称</option><option value="size">按大小</option></select></div><div className="fdDesk_fileHeading"><span>{visible.length} 个结果</span><span>置顶文件优先显示</span></div><div className="fdDesk_fileList">{visible.slice(0, 300).map(file => <article key={file.relative} className={pinned.includes(file.relative) ? 'is-pinned' : ''}><button type="button" className="fdDesk_pin" aria-label={pinned.includes(file.relative) ? `取消置顶${file.name}` : `置顶${file.name}`} onClick={() => togglePin(file.relative)}>{pinned.includes(file.relative) ? '★' : '☆'}</button><span className={`is-${fileKind(file.relative)}`}>{fileKind(file.relative).slice(0, 1).toUpperCase()}</span><div title={file.relative}><strong>{file.name}</strong><small>{file.relative} · {formatSize(file.size)} · {formatDate(file.modifiedAt)}</small></div><button type="button" onClick={() => onReferenceFile(file)}>引用</button><button type="button" onClick={() => onDownloadFile(file)}>下载</button></article>)}{!visible.length && <div className="fdDesk_empty">没有符合条件的文件</div>}</div></div>
}

export function FinanceDashboard({ sessionId, files, workspace, status, onStatus, onRefresh, onOpenWorkspace, onChooseFiles, onChooseFolder, onUploadFiles, onReferenceFile, onDownloadFile, onLaunchWorkflow, launching, onClose }) {
  const today = localDateKey(); const [view, setView] = useState('home'); const [mobileNav, setMobileNav] = useState(false); const [selectedWorkflow, setSelectedWorkflow] = useState(null); const [profile, setProfile] = useStoredState('profile', PROFILE_DEFAULT); const [todosRaw, setTodos] = useStoredState('todos', () => defaultFinanceTodos(today)); const todos = useMemo(() => todosRaw.map(item => normalizeTodo(item, today)), [todosRaw, today]); const [closeTasks, setCloseTasks] = useStoredState('closeTasks', DEFAULT_CLOSE_TASKS); const [favorites, setFavorites] = useStoredState('favorites', ['bank-reconcile', 'invoice-ledger', 'month-close-completeness', 'budget-variance']); const [fieldDictionary, setFieldDictionary] = useStoredState('fieldDictionary', DEFAULT_FIELD_DICTIONARY); const [settings, setSettings] = useStoredState('settings', SETTINGS_DEFAULT); const [snapshots, setSnapshots] = useStoredState('snapshots', []); const [auditLog, setAuditLog] = useStoredState('auditLog', []); const [snapshotDraft, setSnapshotDraft] = useState(() => emptyFinanceSnapshot(PROFILE_DEFAULT.period)); const [workflowQuery, setWorkflowQuery] = useState(''); const [workflowGroup, setWorkflowGroup] = useState('all'); const [newTodo, setNewTodo] = useState({ text: '', category: '通用', due: today, priority: '中' }); const [newField, setNewField] = useState({ name: '', type: '文本', rule: '' }); const importPicker = useRef(null)
  const summary = useMemo(() => summarizeFiles(files), [files]); const progress = useMemo(() => closeProgress(closeTasks), [closeTasks]); const activeTodos = todos.filter(item => !item.done).sort((a, b) => a.due.localeCompare(b.due) || ['高', '中', '低'].indexOf(a.priority) - ['高', '中', '低'].indexOf(b.priority)); const currentSnapshot = useMemo(() => normalizeFinanceSnapshot(snapshots.find(item => item.period === profile.period) || emptyFinanceSnapshot(profile.period), profile.period), [snapshots, profile.period]); const filteredWorkflows = useMemo(() => { const needle = workflowQuery.trim().toLocaleLowerCase('zh-CN'); return FINANCE_WORKFLOWS.filter(item => (workflowGroup === 'all' || item.group === workflowGroup) && (!needle || `${item.title} ${item.role} ${item.desc} ${item.keywords.join(' ')}`.toLocaleLowerCase('zh-CN').includes(needle))) }, [workflowQuery, workflowGroup]); const featured = favorites.map(id => FINANCE_WORKFLOWS.find(item => item.id === id)).filter(Boolean).slice(0, 4)
  const recordEvent = (type, action, detail = '') => setAuditLog(current => [{ id: makeId('audit'), at: new Date().toISOString(), type, action, detail: String(detail).slice(0, 180) }, ...current].slice(0, 200))
  useEffect(() => { setView('home'); setSelectedWorkflow(null); setMobileNav(false) }, [sessionId]); useEffect(() => { setSnapshotDraft(currentSnapshot) }, [profile.period, snapshots])
  const changeView = next => { setView(next); setSelectedWorkflow(null); setMobileNav(false) }; const toggleFavorite = workflowId => { const adding = !favorites.includes(workflowId); setFavorites(current => current.includes(workflowId) ? current.filter(item => item !== workflowId) : [...current, workflowId]); recordEvent('工作流', adding ? '收藏' : '取消收藏', workflowId) }; const selectWorkflow = workflow => { setSelectedWorkflow(workflow); recordEvent('工作流', '打开流程', workflow.title) }; const launchWorkflow = workflow => { recordEvent('工作流', '启动处理', workflow.title); onLaunchWorkflow(workflow) }
  const addTodo = event => { event.preventDefault(); if (!newTodo.text.trim()) return; const todo = normalizeTodo({ ...newTodo, id: makeId('todo') }, today); setTodos(current => [...current, todo]); setNewTodo(current => ({ ...current, text: '' })); recordEvent('待办', '新增', `${todo.category} · ${todo.text}`); onStatus('待办已添加') }
  const saveSnapshot = event => { event.preventDefault(); const value = normalizeFinanceSnapshot(snapshotDraft, profile.period); setSnapshots(current => [...current.filter(item => item.period !== value.period), value].sort((a, b) => a.period.localeCompare(b.period))); recordEvent('总览', '保存经营快照', value.period); onStatus(`${value.period} 经营快照已保存`) }
  const exportData = () => { downloadJson(buildFinanceBackup({ profile, todos, closeTasks, favorites, fieldDictionary, settings, snapshots, auditLog }), `DeepSeek-Harness-财务工作台-${today}.json`); recordEvent('备份', '导出 JSON', today); onStatus('财务工作台 JSON 备份已导出') }
  const importData = file => { const reader = new FileReader(); reader.onload = () => { try { const data = parseFinanceBackup(reader.result); setProfile({ ...PROFILE_DEFAULT, ...data.profile }); setTodos(data.todos.map(item => normalizeTodo(item, today))); setCloseTasks(data.closeTasks); setFavorites(data.favorites); setFieldDictionary(data.fieldDictionary); setSettings({ ...SETTINGS_DEFAULT, ...data.settings }); setSnapshots(Array.isArray(data.snapshots) ? data.snapshots.map(item => normalizeFinanceSnapshot(item)) : []); setAuditLog(Array.isArray(data.auditLog) ? data.auditLog.slice(0, 200) : []); recordEvent('备份', '恢复 JSON', file.name); onStatus('财务工作台备份已恢复') } catch (error) { onStatus(error instanceof Error ? error.message : String(error)) } }; reader.readAsText(file) }
  const frameProps = { view, profile, status, mobileNav, setMobileNav, changeView, onRefresh, onOpenWorkspace, onClose }
  if (selectedWorkflow) return <FinanceDashboardFrame {...frameProps}><WorkflowDetail workflow={selectedWorkflow} files={files} favorites={favorites} launching={launching} onBack={() => setSelectedWorkflow(null)} onFavorite={toggleFavorite} onLaunch={launchWorkflow} onChooseFiles={onChooseFiles} onChooseFolder={onChooseFolder}/></FinanceDashboardFrame>
  let content
  if (view === 'home') content = <OverviewPage profile={profile} snapshot={currentSnapshot} snapshots={snapshots} draft={snapshotDraft} setDraft={setSnapshotDraft} saveSnapshot={saveSnapshot} activeTodos={activeTodos} setTodos={setTodos} progress={progress} closeTasks={closeTasks} featured={featured} favorites={favorites} summary={summary} changeView={changeView} onSelectWorkflow={selectWorkflow}/>
  else if (view === 'todos') content = <div className="fdDesk_page"><Panel title="新增待办" note="明确责任、优先级与截止日期"><form className="fdDesk_todoForm" onSubmit={addTodo}><input value={newTodo.text} onChange={event => setNewTodo(current => ({ ...current, text: event.target.value }))} placeholder="例如：复核本周大额付款资料"/><select value={newTodo.category} onChange={event => setNewTodo(current => ({ ...current, category: event.target.value }))}>{TODO_CATEGORIES.map(item => <option key={item}>{item}</option>)}</select><input type="date" value={newTodo.due} onChange={event => setNewTodo(current => ({ ...current, due: event.target.value }))}/><select value={newTodo.priority} onChange={event => setNewTodo(current => ({ ...current, priority: event.target.value }))}>{['高', '中', '低'].map(item => <option key={item}>{item}</option>)}</select><button type="submit">添加</button></form></Panel><div className="fdDesk_twoCol"><Panel title="待办" note={`${activeTodos.length} 项`}><div className="fdDesk_tasks">{activeTodos.map(item => <article key={item.id}><button type="button" className="fdDesk_check" onClick={() => { setTodos(current => current.map(row => row.id === item.id ? { ...row, done: true } : row)); recordEvent('待办', '完成', item.text) }}/><div><strong>{item.text}</strong><small><span>{item.priority}优先</span>{item.category} · {dueLabel(item.due, today)}</small></div><button type="button" onClick={() => { setTodos(current => current.filter(row => row.id !== item.id)); recordEvent('待办', '删除', item.text) }}>×</button></article>)}{!activeTodos.length && <div className="fdDesk_empty">暂无待办</div>}</div></Panel><Panel title="已完成" note={`${todos.filter(item => item.done).length} 项`}><div className="fdDesk_tasks">{todos.filter(item => item.done).map(item => <article className="is-done" key={item.id}><button type="button" className="fdDesk_check" onClick={() => { setTodos(current => current.map(row => row.id === item.id ? { ...row, done: false } : row)); recordEvent('待办', '恢复', item.text) }}>✓</button><div><strong>{item.text}</strong><small>{item.category} · {item.due}</small></div><button type="button" onClick={() => { setTodos(current => current.filter(row => row.id !== item.id)); recordEvent('待办', '删除', item.text) }}>×</button></article>)}</div></Panel></div></div>
  else if (view === 'workflows') content = <div className="fdDesk_page"><div className="fdDesk_workflowTools"><input value={workflowQuery} onChange={event => setWorkflowQuery(event.target.value)} placeholder="搜索场景、岗位、业务关键词"/><div>{WORKFLOW_GROUPS.map(([id, label]) => <button type="button" key={id} className={workflowGroup === id ? 'is-active' : ''} onClick={() => setWorkflowGroup(id)}>{label}</button>)}</div></div><WorkflowCards workflows={filteredWorkflows} favorites={favorites} onSelect={selectWorkflow}/></div>
  else if (FINANCE_MODULES[view] && view !== 'audit') { const module = FINANCE_MODULES[view]; const workflows = module.workflowIds.map(id => FINANCE_WORKFLOWS.find(item => item.id === id)).filter(Boolean); content = <ManagementModulePage module={module} snapshot={currentSnapshot} todos={todos} workflows={workflows} favorites={favorites} onSelect={selectWorkflow} onNewTodo={() => { setNewTodo(current => ({ ...current, category: module.todoCategories[0] || '通用' })); changeView('todos') }} onFiles={() => changeView('files')}/> }
  else if (view === 'audit') content = <div className="fdDesk_page"><div className="fdDesk_moduleHero fdDesk_moduleHeroPro"><div><small>AUDIT TRAIL · 治理与系统</small><h1>关键动作有迹可循</h1><p>记录工作台内的新增、恢复、启动、收藏和设置变更；日志仅保存在本机。</p></div><span>{auditLog.length}<small>条本机记录</small></span></div><Panel title="操作日志" note="最多保留最近 200 条" action={<button className="fdDesk_textButton" type="button" onClick={() => downloadJson(auditLog, `财务工作台-审计日志-${today}.json`)}>导出日志</button>}><div className="fdDesk_auditList">{auditLog.map(item => <article key={item.id}><time>{formatDate(item.at)}</time><span>{item.type}</span><div><strong>{item.action}</strong>{item.detail && <small>{item.detail}</small>}</div></article>)}{!auditLog.length && <div className="fdDesk_empty">完成一次新增、备份或工作流操作后，这里会出现留痕。</div>}</div></Panel></div>
  else if (view === 'close') content = <div className="fdDesk_page"><div className="fdDesk_moduleHero fdDesk_moduleHeroPro"><div><small>MONTH-END CONTROL</small><h1>月结不是“做完”，而是“有证据地完成”</h1><p>逐项确认责任人、证据、差异状态与预计完成时间。</p></div><span>{progress.percent}%<small>完成度</small></span></div><div className="fdDesk_closeGrid"><Panel title="月结任务清单" note="勾选表示已取得完成证据"><div className="fdDesk_closeTasks">{closeTasks.map(item => <label key={item.id} className={item.done ? 'is-done' : ''}><input type="checkbox" checked={item.done} onChange={() => { setCloseTasks(current => current.map(row => row.id === item.id ? { ...row, done: !row.done } : row)); recordEvent('月结', item.done ? '撤销完成' : '确认完成', item.title) }}/><span><strong>{item.title}</strong><small>{item.owner} · 证据：{item.evidence}</small></span></label>)}</div></Panel><Panel title="适用工作流" note="异常检查、资料完整性和归档"><WorkflowCards workflows={workflowsForView(FINANCE_WORKFLOWS, 'close')} favorites={favorites} onSelect={selectWorkflow}/></Panel></div></div>
  else if (view === 'files') content = <FileLibrary files={files} workspace={workspace} onOpenWorkspace={onOpenWorkspace} onChooseFiles={onChooseFiles} onChooseFolder={onChooseFolder} onUploadFiles={onUploadFiles} onReferenceFile={onReferenceFile} onDownloadFile={onDownloadFile} onStatus={onStatus} onAudit={recordEvent}/>
  else if (view === 'backup') content = <div className="fdDesk_page"><div className="fdDesk_backupHero"><small>LOCAL-FIRST BACKUP</small><h1>把可复刻的数据带走</h1><p>备份经营快照、待办、月结清单、收藏、字段字典、阈值和审计日志；财务原始资料继续留在工作区目录。</p><div><button type="button" onClick={exportData}>导出 JSON 备份</button><button type="button" className="is-secondary" onClick={() => importPicker.current?.click()}>恢复 JSON 备份</button></div></div><div className="fdDesk_backupStats">{[[snapshots.length, '经营期间'], [todos.length, '待办记录'], [fieldDictionary.length, '字段规则'], [auditLog.length, '审计日志']].map(([value, label]) => <article key={label}><strong>{value}</strong><span>{label}</span></article>)}</div><Panel title="新手恢复说明" note="先导出一份当前备份，再导入历史文件"><ol className="fdDesk_restoreSteps"><li><span>1</span><div><strong>导出当前数据</strong><small>保留一份恢复前的回滚副本。</small></div></li><li><span>2</span><div><strong>选择 JSON 文件</strong><small>系统会先检查产品标识和数据结构。</small></div></li><li><span>3</span><div><strong>核对主体与期间</strong><small>恢复后检查首页数字、待办和字段字典。</small></div></li></ol></Panel><input ref={importPicker} hidden type="file" accept="application/json,.json" onChange={event => { const file = event.target.files?.[0]; event.target.value = ''; if (file) importData(file) }}/></div>
  else content = <div className="fdDesk_page"><div className="fdDesk_settingsGrid"><Panel title="个人与期间设置" note="仅用于本机工作台显示"><div className="fdDesk_settingsForm"><label>称呼<input value={profile.name} onChange={event => setProfile(current => ({ ...current, name: event.target.value }))}/></label><label>主体 / 工作区<input value={profile.entity} onChange={event => setProfile(current => ({ ...current, entity: event.target.value }))}/></label><label>岗位定位<input value={profile.role} onChange={event => setProfile(current => ({ ...current, role: event.target.value }))}/></label><label>当前期间<input type="month" value={profile.period} onChange={event => setProfile(current => ({ ...current, period: event.target.value }))}/></label></div></Panel><Panel title="关键阈值" note="用于筛选和提醒，不替代财务判断"><div className="fdDesk_settingsForm"><label>大额提醒（元）<input type="number" min="0" value={settings.largeAmount} onChange={event => setSettings(current => ({ ...current, largeAmount: Number(event.target.value) }))}/></label><label>对账日期容差（天）<input type="number" min="0" max="31" value={settings.dateTolerance} onChange={event => setSettings(current => ({ ...current, dateTolerance: Number(event.target.value) }))}/></label><label>异常变化阈值（%）<input type="number" min="0" value={settings.varianceRate} onChange={event => setSettings(current => ({ ...current, varianceRate: Number(event.target.value) }))}/></label></div></Panel></div><Panel title="字段字典" note="把口头经验写成可重复使用的字段规则"><div className="fdDesk_dictionary">{fieldDictionary.map(item => <article key={item.id}><div><strong>{item.name}</strong><small>{item.type}</small></div><p>{item.rule}</p><button type="button" onClick={() => { setFieldDictionary(current => current.filter(row => row.id !== item.id)); recordEvent('设置', '删除字段规则', item.name) }}>×</button></article>)}</div><form className="fdDesk_fieldForm" onSubmit={event => { event.preventDefault(); if (!newField.name.trim() || !newField.rule.trim()) return; setFieldDictionary(current => [...current, { ...newField, id: makeId('field') }]); recordEvent('设置', '新增字段规则', newField.name); setNewField({ name: '', type: '文本', rule: '' }); onStatus('字段规则已添加') }}><input value={newField.name} onChange={event => setNewField(current => ({ ...current, name: event.target.value }))} placeholder="字段名称"/><select value={newField.type} onChange={event => setNewField(current => ({ ...current, type: event.target.value }))}>{['文本', '数值', '日期', '枚举', '布尔'].map(item => <option key={item}>{item}</option>)}</select><input value={newField.rule} onChange={event => setNewField(current => ({ ...current, rule: event.target.value }))} placeholder="口径、必填、唯一性或取值规则"/><button type="submit">添加字段</button></form></Panel><Panel title="8 步自动化搭建法" note="先诊断、后执行；先小样本、后全量"><div className="fdDesk_sopGrid">{SOP_STEPS.map(([no, title, note]) => <article key={no}><span>{no}</span><div><strong>{title}</strong><small>{note}</small></div></article>)}</div></Panel></div>
  return <FinanceDashboardFrame {...frameProps}>{content}</FinanceDashboardFrame>
}

function FinanceDashboardFrame({ view, profile, status, mobileNav, setMobileNav, changeView, onRefresh, onOpenWorkspace, onClose, children }) {
  const meta = PAGE_META[view] || ['财务工作台', '专业财务自动化与经营管理']; const utility = [['todos', '待办'], ['workflows', '工作流'], ['files', '资料库'], ['close', '月结']]
  return <section className="dfinance_panel dfinance_embedded fdDesk_root" aria-label="财务工作台"><aside className={`fdDesk_sidebar ${mobileNav ? 'is-open' : ''}`}><div className="fdDesk_identity"><span>财</span><div><strong>财务管理工作台</strong><small>{profile.entity}</small></div><button type="button" onClick={() => setMobileNav(false)} aria-label="关闭导航">×</button></div><nav aria-label="财务工作台导航">{NAV_GROUPS.map((group, index) => <div className="fdDesk_navGroup" key={group.label || index}>{group.label && <small>{group.label}</small>}{group.items.map(([key, label, icon]) => <button type="button" key={key} className={view === key ? 'is-active' : ''} onClick={() => changeView(key)}><span>{icon}</span><strong>{label}</strong></button>)}</div>)}</nav><footer><strong>{profile.period}</strong><span><i/>数据与设置保存在本机</span></footer></aside>{mobileNav && <button type="button" className="fdDesk_mobileMask" aria-label="关闭导航蒙层" onClick={() => setMobileNav(false)}/>}<div className="fdDesk_main"><header className="fdDesk_topbar"><button type="button" className="fdDesk_menu" onClick={() => setMobileNav(true)} aria-label="打开导航">☰</button><div><h2>{meta[0]}</h2><p>{meta[1]}</p></div><div className="fdDesk_toolNav">{utility.map(([key, label]) => <button type="button" key={key} className={view === key ? 'is-active' : ''} onClick={() => changeView(key)}>{label}</button>)}</div><span>{new Date().toLocaleDateString('zh-CN', { month: 'long', day: 'numeric', weekday: 'short' })}</span><button type="button" className="fdDesk_return" onClick={onClose}>返回对话</button></header><div className="fdDesk_status"><i/><span>{status}</span><button type="button" onClick={onOpenWorkspace}>打开目录</button><button type="button" onClick={onRefresh}>刷新</button></div><main className="fdDesk_content">{children}</main></div></section>
}
